import {readFileSync, existsSync} from 'node:fs';
import {createHash} from 'node:crypto';
import assert from 'node:assert/strict';
const read = path => readFileSync(new URL('../'+path, import.meta.url),'utf8');
const html=read('index.html'), notFound=read('404.html'), sw=read('sw.js'), map=read('FEATURE-MAP.md');
const blocks=[...html.matchAll(/<script(?:[^>]*)>([\s\S]*?)<\/script>/g)].map(m=>m[1]);
const csp=html.match(/Content-Security-Policy" content="([^"]+)/)?.[1];
assert(csp,'CSP missing');
for(const script of blocks)assert(csp.includes("'sha256-"+createHash('sha256').update(script).digest('base64')+"'"),'CSP script hash mismatch');
assert(html.includes('<title>EDGE//AI |') && html.includes('<meta name="description"'),'Main page metadata missing');
assert(notFound.includes('<title>Page not found | EDGE//AI') && notFound.includes('href="/edge-ai/"'),'404 metadata/back link missing');
assert(html.includes('href="./favicon.svg"') && notFound.includes('href="/edge-ai/favicon.svg"'),'Favicon missing');
assert(existsSync(new URL('../favicon.svg',import.meta.url)),'Favicon file missing');
assert(sw.includes("'./404.html'") && sw.includes("'./favicon.svg'"),'Offline shell lacks 404 or icon');
assert(map.includes('Surface quality and release checklist'),'Feature map checklist missing');
assert(!html.includes('data.error?.message') && !html.includes('data.detail||data.message'),'Raw remote error body exposed');
assert(!html.includes('console.error('),'Console stack trace exposure');
assert(!html.includes('naksh@example.com') && !html.includes('+91 98765 43210'),'Identifying example copy remains');
assert(read('chat-worker.js').includes('ENGINE_SHA384'),'Worker integrity gate missing');
assert(html.includes("if(task==='chat') throw new Error('Chat models load in the dedicated worker')"),'Main-thread chat load path returned');
console.log('Surface checks PASS: CSP, metadata, icon, 404, feature-map, remote error boundary, worker hash');
