import {readFileSync, existsSync} from 'node:fs';
import {createHash} from 'node:crypto';
import assert from 'node:assert/strict';
const read = path => readFileSync(new URL('../'+path, import.meta.url),'utf8');
const html=read('index.html'), notFound=read('404.html'), sw=read('sw.js'), map=read('FEATURE-MAP.md');
const blocks=[...html.matchAll(/<script(?:[^>]*)>([\s\S]*?)<\/script>/g)].map(m=>m[1]);
const csp=html.match(/Content-Security-Policy" content="([^"]+)/)?.[1];
assert(csp,'CSP missing');
for(const script of blocks)assert(csp.includes("'sha256-"+createHash('sha256').update(script).digest('base64')+"'"),'CSP script hash mismatch');
assert(html.includes('<title>EDGE//AI |') && html.includes('<meta name="description"'),'Main page metadata missing');
assert(notFound.includes('<title>Page not found | EDGE//AI') && notFound.includes('href="/edge-ai/"'),'404 metadata/back link missing');
assert(html.includes('href="./favicon.svg"') && notFound.includes('href="/edge-ai/favicon.svg"'),'Favicon missing');
assert(existsSync(new URL('../favicon.svg',import.meta.url)),'Favicon file missing');
assert(sw.includes("'./404.html'") && sw.includes("'./favicon.svg'"),'Offline shell lacks 404 or icon');
assert(map.includes('Surface quality and release checklist'),'Feature map checklist missing');
assert(!html.includes('data.error?.message') && !html.includes('data.detail||data.message'),'Raw remote error body exposed');
assert(!html.includes('console.error('),'Console stack trace exposure');
assert(!html.includes('naksh@example.com') && !html.includes('+91 98765 43210'),'Identifying example copy remains');
assert(read('chat-worker.js').includes('ENGINE_SHA384'),'Worker integrity gate missing');
assert(html.includes("if(task==='chat') throw new Error('Chat models load in the dedicated worker')"),'Main-thread chat load path returned');
const worker=read('chat-worker.js');
assert(worker.includes("data.dtype || 'q4'") && !worker.includes("data.dtype || 'q4f16'"),'Default WebGPU dtype must be q4');
assert(worker.includes('sanityProbe()') && worker.includes('looksLikeText'),'Post-load output sanity probe missing');
const looks=new Function(worker.match(/function looksLikeText[\s\S]*?\n}\n/)[0]+'return looksLikeText;')();
for(const bad of ['.8/0+',"23'#+>@@+=.)7-/2;=:++*$5'#?",'1','',null,'9?<.-;9+;!;>:>/4;7/#7)"0A<.79@7-*@@-'])assert(!looks(bad),'garbage accepted: '+bad);
for(const good of ['ready','Ready.','Hello! How can I help?','\u0928\u092e\u0938\u094d\u0924\u0947'])assert(looks(good),'real text rejected: '+good);
assert(sw.includes('edge-shell-v22'),'Service worker cache not bumped for worker fix');
console.log('Surface checks PASS: CSP, metadata, icon, 404, feature-map, remote error boundary, worker hash');
